/****** Object:  Table [ADWViews].[CUST_HIER_D_View]    Script Date: 4/3/2019 11:57:04 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE EXTERNAL TABLE [ADWViews].[CUST_HIER_D_View]
(
	[CUST_ID] [varchar](30) NOT NULL,
	[CUST_AMID_LVL_2_ID] [varchar](15) NOT NULL,
	[CUST_AMID_LVL_2_HSTD_GEO_CD] [varchar](10) NULL,
	[CUST_AMID_LVL_3_HSTD_GEO_CD] [varchar](10) NULL,
	[CUST_AMID_LVL_4_HSTD_GEO_CD] [varchar](10) NULL,
	[CUST_AMID_LVL_2_SEG_CD] [varchar](3) NULL,
	[CUST_AMID_LVL_3_SEG_CD] [varchar](3) NULL,
	[CUST_AMID_LVL_4_SEG_CD] [varchar](3) NULL,
	[CUST_AMID_LVL_2_NM] [nvarchar](105) NULL,
	[CUST_AMID_LVL_2_SHT_NM] [nvarchar](20) NULL,
	[CUST_AMID_LVL_2_IND_VERT_CD] [varchar](3) NULL,
	[CUST_AMID_LVL_2_IND_VERT_NM] [nvarchar](50) NULL,
	[CUST_AMID_LVL_2_IND_SEG_CD] [varchar](3) NULL,
	[CUST_AMID_LVL_2_IND_SEG_NM] [nvarchar](50) NULL,
	[CUST_AMID_LVL_2_CLS_1_CD] [varchar](3) NULL,
	[CUST_AMID_LVL_2_CLS_1_NM] [nvarchar](50) NULL,
	[CUST_AMID_LVL_2_CLS_2_CD] [varchar](3) NULL,
	[CUST_AMID_LVL_2_CLS_2_NM] [nvarchar](50) NULL,
	[CUST_AMID_LVL_2_SUB_CLS_1_CD] [varchar](3) NULL,
	[CUST_AMID_LVL_2_SUB_CLS_1_NM] [nvarchar](50) NULL,
	[CUST_AMID_LVL_2_SUB_CLS_2_CD] [varchar](3) NULL,
	[CUST_AMID_LVL_2_SUB_CLS_2_NM] [nvarchar](50) NULL,
	[CUST_AMID_LVL_2_GBL_ACCT_CD] [nvarchar](50) NULL,
	[CUST_AMID_LVL_3_ID] [varchar](15) NULL,
	[CUST_AMID_LVL_3_NM] [nvarchar](105) NULL,
	[CUST_AMID_LVL_3_SHT_NM] [nvarchar](20) NULL,
	[CUST_AMID_LVL_3_IND_VERT_CD] [varchar](3) NULL,
	[CUST_AMID_LVL_3_IND_VERT_NM] [nvarchar](50) NULL,
	[CUST_AMID_LVL_3_IND_SEG_CD] [varchar](3) NULL,
	[CUST_AMID_LVL_3_IND_SEG_NM] [nvarchar](50) NULL,
	[CUST_AMID_LVL_3_CLS_1_CD] [varchar](3) NULL,
	[CUST_AMID_LVL_3_CLS_1_NM] [nvarchar](50) NULL,
	[CUST_AMID_LVL_3_CLS_2_CD] [varchar](3) NULL,
	[CUST_AMID_LVL_3_CLS_2_NM] [nvarchar](50) NULL,
	[CUST_AMID_LVL_3_SUB_CLS_1_CD] [varchar](3) NULL,
	[CUST_AMID_LVL_3_SUB_CLS_1_NM] [nvarchar](50) NULL,
	[CUST_AMID_LVL_3_SUB_CLS_2_CD] [varchar](3) NULL,
	[CUST_AMID_LVL_3_SUB_CLS_2_NM] [nvarchar](50) NULL,
	[CUST_AMID_LVL_3_GBL_ACCT_CD] [nvarchar](50) NULL,
	[CUST_AMID_LVL_4_ID] [varchar](15) NULL,
	[CUST_AMID_LVL_4_NM] [nvarchar](105) NULL,
	[CUST_AMID_LVL_4_SHT_NM] [nvarchar](20) NULL,
	[CUST_AMID_LVL_4_IND_VERT_CD] [varchar](3) NULL,
	[CUST_AMID_LVL_4_IND_VERT_NM] [nvarchar](50) NULL,
	[CUST_AMID_LVL_4_IND_SEG_CD] [varchar](3) NULL,
	[CUST_AMID_LVL_4_IND_SEG_NM] [nvarchar](50) NULL,
	[CUST_AMID_LVL_4_CLS_1_CD] [varchar](3) NULL,
	[CUST_AMID_LVL_4_CLS_1_NM] [nvarchar](50) NULL,
	[CUST_AMID_LVL_4_CLS_2_CD] [varchar](3) NULL,
	[CUST_AMID_LVL_4_CLS_2_NM] [nvarchar](50) NULL,
	[CUST_AMID_LVL_4_SUB_CLS_1_CD] [varchar](3) NULL,
	[CUST_AMID_LVL_4_SUB_CLS_1_NM] [nvarchar](50) NULL,
	[CUST_AMID_LVL_4_SUB_CLS_2_CD] [varchar](3) NULL,
	[CUST_AMID_LVL_4_SUB_CLS_2_NM] [nvarchar](50) NULL,
	[CUST_AMID_LVL_4_GBL_ACCT_CD] [nvarchar](50) NULL,
	[CID_SITE_ID] [varchar](10) NOT NULL,
	[CID_SUB_SITE_ID] [varchar](5) NULL,
	[CUST_NM] [nvarchar](120) NULL,
	[CUST_RELSHP_PRFL_ID] [varchar](30) NOT NULL,
	[CUST_SLS_BUS_UNIT_CD] [varchar](5) NULL,
	[CUST_SLS_BUS_UNIT_EMP_BADGE_ID] [varchar](8) NULL,
	[CUST_SLS_BUS_UNIT_NM] [nvarchar](35) NULL,
	[CUST_SLS_DIST_CD] [varchar](5) NULL,
	[CUST_SLS_DIST_EMP_BADGE_ID] [varchar](8) NULL,
	[CUST_SLS_DIST_NM] [nvarchar](35) NULL,
	[CUST_SLS_DIV_CD] [varchar](5) NULL,
	[CUST_SLS_DIV_EMP_BADGE_ID] [varchar](8) NULL,
	[CUST_SLS_DIV_NM] [nvarchar](35) NULL,
	[CUST_SLS_RGN_CD] [varchar](5) NULL,
	[CUST_SLS_RGN_EMP_BADGE_ID] [varchar](8) NULL,
	[CUST_SLS_RGN_NM] [nvarchar](35) NULL,
	[CUST_SLS_UNIT_CD] [varchar](5) NOT NULL,
	[CUST_SLS_UNIT_EMP_BADGE_ID] [varchar](8) NULL,
	[CUST_SLS_UNIT_NM] [nvarchar](35) NULL,
	[DNB_BUS_NM] [nvarchar](120) NULL,
	[DNB_DOM_ULTM_BUS_NM] [nvarchar](120) NULL,
	[DNB_DOM_ULTM_DUNS_ID] [varchar](9) NULL,
	[DNB_GBL_ULTM_BUS_NM] [nvarchar](120) NULL,
	[DNB_GBL_ULTM_DUNS_ID] [varchar](9) NULL,
	[DNB_HQ_BUS_NM] [nvarchar](120) NULL,
	[DNB_HQ_DUNS_ID] [varchar](9) NULL,
	[DNB_PARNT_BUS_NM] [nvarchar](120) NULL,
	[DNB_PARNT_DUNS_ID] [varchar](9) NULL,
	[DNB_PRIM_TRD_STY_NM] [nvarchar](120) NULL,
	[DNB_SITE_DUNS_ID] [varchar](9) NOT NULL,
	[GEO_CD] [varchar](10) NOT NULL,
	[SRC_ADDR_LN_1_TX] [nvarchar](200) NULL,
	[SRC_ADDR_LN_2_TX] [nvarchar](100) NULL,
	[SRC_ADDR_LN_3_TX] [nvarchar](100) NULL,
	[SRC_CITY_AREA_NM] [nvarchar](50) NULL,
	[SRC_CITY_NM] [nvarchar](50) NULL,
	[SRC_CO_DIV_NM] [nvarchar](100) NULL,
	[SRC_COMPET_CD] [varchar](1) NULL,
	[SRC_CUST_CD] [varchar](1) NULL,
	[SRC_CUST_SEG_CD] [varchar](3) NULL,
	[SRC_CUST_SEG_NM] [nvarchar](50) NULL,
	[SRC_IND_SEG_CD] [varchar](3) NULL,
	[SRC_IND_SEG_NM] [nvarchar](50) NULL,
	[SRC_IND_VERT_CD] [varchar](3) NULL,
	[SRC_IND_VERT_NM] [nvarchar](50) NULL,
	[SRC_PHONE_NR_ID] [varchar](45) NULL,
	[SRC_POST_CD] [varchar](16) NULL,
	[SRC_PTNR_CD] [varchar](1) NULL,
	[SRC_PTNR_CHNL_CD] [varchar](4) NULL,
	[SRC_ST_PRVNC_NM] [nvarchar](30) NULL,
	[SRC_VNDR_CD] [varchar](1) NULL,
	[STD_ADDR_LN_1_TX] [nvarchar](200) NULL,
	[STD_ADDR_LN_2_TX] [nvarchar](100) NULL,
	[STD_ADDR_LN_3_TX] [nvarchar](100) NULL,
	[STD_BLDG_NM] [nvarchar](42) NULL,
	[STD_CITY_NM] [nvarchar](80) NULL,
	[STD_GEO_AREA_NM] [nvarchar](80) NULL,
	[STD_GEO_SUB_AREA_NM] [nvarchar](80) NULL,
	[STD_POST_ADDR_BOX_ID] [varchar](9) NULL,
	[STD_POST_ADDR_NM] [nvarchar](80) NULL,
	[STD_POST_BOX_LABEL_NM] [nvarchar](41) NULL,
	[STD_POST_CD] [varchar](16) NULL,
	[STD_ST_PRVNC_NM] [nvarchar](80) NULL,
	[STD_STR_ADDR_NM] [nvarchar](100) NULL,
	[STD_STR_DESIG_NM] [nvarchar](60) NULL,
	[INS_GMT_TS] [datetime2](7) NULL,
	[LOAD_JOB_NR] [decimal](18, 0) NULL,
	[UPD_GMT_TS] [datetime2](7) NULL,
	[REC_ST_NR] [smallint] NULL,
	[ACT_FG] [varchar](1) NOT NULL,
	[STBNG_FG] [varchar](1) NOT NULL,
	[OTHR_PARTY_SITE_ID] [bigint] NOT NULL,
	[OTHR_PARTY_SITE_INSTNC_ID] [bigint] NOT NULL
)
WITH (DATA_SOURCE = [crmalesADWDS])
GO