/****** Object:  Table [ADWViews].[DT_DAY_D_View]    Script Date: 4/3/2019 11:57:16 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE EXTERNAL TABLE [ADWViews].[DT_DAY_D_View]
(
	[CLDR_DT] [date] NULL,
	[CLDR_DT_YYYYMMDD_CD] [varchar](8) NULL,
	[CLDR_DT_DD_MON_YYYY_CD] [varchar](11) NULL,
	[CLDR_DT_DD_MM_YYYY_CD] [varchar](10) NULL,
	[CLDR_DT_MM_DD_YYYY_CD] [varchar](10) NULL,
	[CLDR_DT_YYYY_MM_DD_CD] [varchar](10) NULL,
	[CLDR_DAY_CD] [varchar](3) NULL,
	[CLDR_DAY_NM] [varchar](9) NULL,
	[CLDR_ISO_YR_WEEK_CD] [varchar](6) NULL,
	[CLDR_ISO_WEEK_STRT_DT] [date] NULL,
	[CLDR_ISO_WEEK_END_DT] [date] NULL,
	[CLDR_SAT_TO_FRI_WEEK_STRT_DT] [date] NULL,
	[CLDR_SAT_TO_FRI_WEEK_END_DT] [date] NULL,
	[CLDR_SUN_TO_SAT_WEEK_STRT_DT] [date] NULL,
	[CLDR_SUN_TO_SAT_WEEK_END_DT] [date] NULL,
	[CLDR_TUE_TO_MON_STRT_DT] [date] NULL,
	[CLDR_TUE_TO_MON_WEEK_END_DT] [date] NULL,
	[CLDR_WED_TO_TUE_WEEK_END_DT] [date] NULL,
	[CLDR_THU_TO_WED_WEEK_END_DT] [date] NULL,
	[CLDR_FRI_TO_THU_WEEK_STRT_DT] [date] NULL,
	[CLDR_FRI_TO_THU_WEEK_END_DT] [date] NULL,
	[CLDR_MTH_ABBR_CD] [varchar](3) NULL,
	[CLDR_MTH_NM] [nvarchar](9) NULL,
	[CLDR_YR_MTH_CD] [varchar](6) NULL,
	[CLDR_YR_MTH_DSPLY_CD] [varchar](7) NULL,
	[CLDR_MTH_STRT_DT] [date] NULL,
	[CLDR_MTH_END_DT] [date] NULL,
	[CLDR_LAST_DAY_OF_MTH_FG] [varchar](1) NULL,
	[CLDR_QTR_CD] [varchar](2) NULL,
	[CLDR_QTR_YR_CD] [varchar](5) NULL,
	[CLDR_YR_QTR_CD] [varchar](6) NULL,
	[CLDR_YR_QTR_DSPLY_CD] [varchar](7) NULL,
	[CLDR_QTR_STRT_DT] [date] NULL,
	[CLDR_QTR_END_DT] [date] NULL,
	[CLDR_LAST_DAY_OF_QTR_FG] [varchar](1) NULL,
	[CLDR_HALF_CD] [varchar](2) NULL,
	[CLDR_HALF_YR_CD] [varchar](5) NULL,
	[CLDR_YR_HALF_CD] [varchar](6) NULL,
	[CLDR_HALF_STRT_DT] [date] NULL,
	[CLDR_HALF_END_DT] [date] NULL,
	[CLDR_LAST_DAY_OF_HALF_FG] [varchar](1) NULL,
	[CLDR_YR_STRT_DT] [date] NULL,
	[CLDR_YR_END_DT] [date] NULL,
	[CLDR_YR_NR] [decimal](4, 0) NULL,
	[CLDR_LAST_DAY_OF_YR_FG] [varchar](1) NULL,
	[FISC_YR_WEEK_CD] [varchar](6) NULL,
	[FISC_MTH_YR_CD] [varchar](6) NULL,
	[FISC_YR_MTH_CD] [varchar](8) NULL,
	[FISC_YR_MTH_DSPLY_CD] [varchar](9) NULL,
	[FISC_QTR_CD] [varchar](2) NULL,
	[FISC_QTR_YR_CD] [varchar](5) NULL,
	[FISC_YR_QTR_CD] [varchar](8) NULL,
	[FISC_YR_QTR_DSPLY_CD] [varchar](9) NULL,
	[FISC_QTR_STRT_DT] [date] NULL,
	[FISC_QTR_END_DT] [date] NULL,
	[FISC_LAST_DAY_OF_QTR_FG] [varchar](1) NULL,
	[FISC_HALF_CD] [varchar](2) NULL,
	[FISC_HALF_YR_CD] [varchar](5) NULL,
	[FISC_YR_HALF_CD] [varchar](8) NULL,
	[FISC_HALF_STRT_DT] [date] NULL,
	[FISC_HALF_END_DT] [date] NULL,
	[FISC_LAST_DAY_OF_HALF_FG] [varchar](1) NULL,
	[FISC_YR_NM] [varchar](6) NULL,
	[FISC_YR_STRT_DT] [date] NULL,
	[FISC_YR_END_DT] [date] NULL,
	[FISC_LAST_DAY_OF_YR_FG] [varchar](1) NULL,
	[WKDY_FG] [varchar](1) NULL,
	[WKEND_DT_FG] [varchar](1) NULL,
	[SAB101_DT_FG] [varchar](1) NULL,
	[SAB101_CLDR_QTR_CD] [varchar](2) NULL,
	[SAB101_FISC_QTR_CD] [varchar](2) NULL,
	[SAB101_CLDR_MTH_END_DT] [date] NULL,
	[SAB101_CLDR_MTH_CD] [varchar](3) NULL,
	[SAB101_CLDR_MTH_NM] [nvarchar](9) NULL,
	[PAST_30_DAYS_FG] [varchar](1) NULL,
	[PAST_60_DAYS_FG] [varchar](1) NULL,
	[PAST_90_DAYS_FG] [varchar](1) NULL,
	[PAST_120_DAYS_FG] [varchar](1) NULL,
	[RLTV_MTH_NR] [int] NULL,
	[RLTV_QTR_NR] [int] NULL,
	[RLTV_YR_NR] [int] NULL,
	[RLTV_FISC_QTR_NR] [int] NULL,
	[RLTV_FISC_YR_NR] [int] NULL,
	[INS_GMT_TS] [datetime2](7) NULL,
	[UPD_GMT_TS] [datetime2](7) NULL,
	[SRC_SYS_KY] [bigint] NULL,
	[ACT_FG] [varchar](1) NULL,
	[STBNG_FG] [varchar](1) NULL,
	[LGCL_DEL_FG] [varchar](1) NULL,
	[LOAD_JOB_NR] [decimal](18, 0) NULL,
	[SRC_SYS_UPD_TS] [datetime2](7) NULL,
	[SRC_SYS_BTCH_NR] [decimal](15, 0) NULL,
	[SRC_SYS_EXTRC_GMT_TS] [datetime2](7) NULL,
	[REC_ST_NR] [smallint] NULL,
	[FISC_HARD_CLOSE_DT] [date] NULL,
	[FISC_YR_FIN_STRT_DT] [date] NULL,
	[CLDR_MTH_NR] [decimal](2, 0) NULL,
	[CLDR_QTR_NR] [decimal](1, 0) NULL,
	[FISC_QTR_NR] [decimal](1, 0) NULL,
	[FISC_HALF_NR] [decimal](1, 0) NULL,
	[FISC_YR_NR] [decimal](4, 0) NULL,
	[RLTV_FISC_HALF_NR] [int] NULL,
	[CLDR_MTH_YR_CD] [varchar](6) NULL
)
WITH (DATA_SOURCE = [crmalesADWDS])
GO