CREATE TABLE [dbo].[Table1]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [EMAIL] NVARCHAR(50) NULL, 
    [FIRSTNAME] NVARCHAR(50) NULL, 
    [LASTNAME] NVARCHAR(50) NULL, 
    [FATHERNAME] NVARCHAR(50) NULL,
	[rollnum] NVARCHAR(50) NULL
)
